# Generated by Django 3.2 on 2021-05-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('w', 'WBS-Element'), ('o', 'Order Number'), ('c', 'Cost Center item number')], max_length=1)),
                ('vunetid', models.CharField(max_length=6)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Datamanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('vunetid', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('institute', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('request_date', models.DateField()),
                ('delete_date', models.DateField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.budget')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.department')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('yoda_name', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('deleted', models.DateTimeField()),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='VaultFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yoda_name', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('deleted', models.DateTimeField()),
                ('research_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.researchfolder')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='orcid',
            field=models.CharField(max_length=19),
        ),
        migrations.CreateModel(
            name='VaultStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.BigIntegerField()),
                ('created', models.DateTimeField()),
                ('research_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.vaultfolder')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.BigIntegerField()),
                ('created', models.DateTimeField()),
                ('research_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.researchfolder')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yoda_id', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('deleted', models.DateTimeField()),
                ('vault_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.vaultfolder')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to='projects.person'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to='projects.person'),
        ),
    ]
