# Generated by Django 3.2 on 2021-05-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='yoda_id',
            field=models.CharField(max_length=30),
        ),
    ]
