# Generated by Django 3.2 on 2021-05-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_publications_yoda_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
