# Generated by Django 3.2 on 2021-05-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_publications_doi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaultstats',
            old_name='research_folder',
            new_name='vault_folder',
        ),
    ]
