# Generated by Django 3.2 on 2021-05-18 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_research_folder_vaultstats_vault_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultdataset',
            name='vault_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.vaultfolder'),
        ),
    ]
