# Generated by Django 3.2 on 2021-05-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_vaultdataset_vault_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultdataset',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Publications',
        ),
    ]
