# Generated by Django 3.2 on 2021-06-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20210531_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_total', models.BigIntegerField()),
                ('users_total', models.IntegerField()),
                ('collected', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
