# Generated by Django 3.2 on 2021-06-07 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_miscstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscstats',
            name='revision_size',
            field=models.BigIntegerField(0),
            preserve_default=False,
        ),
    ]
