# Generated by Django 3.2.4 on 2021-06-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210614_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscstats',
            name='projects_total',
            field=models.IntegerField(default=6),
        ),
    ]
