# Generated by Django 3.2.4 on 2021-06-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_miscstats_projects_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscstats',
            name='datasets_total',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='miscstats',
            name='groups_total',
            field=models.IntegerField(default=17),
        ),
        migrations.AddField(
            model_name='miscstats',
            name='published_total',
            field=models.IntegerField(default=0),
        ),
    ]
