# Generated by Django 3.2.4 on 2021-06-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_miscstats_trash_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscstats',
            name='size_research',
            field=models.BigIntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miscstats',
            name='size_vault',
            field=models.BigIntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
