# Generated by Django 3.2.4 on 2021-06-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20210616_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin_remarks',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='requested_size',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='project',
            name='storage_limit',
            field=models.IntegerField(default=500),
        ),
    ]
