# Generated by Django 3.2.4 on 2021-06-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20210617_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='admin_remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
