# Generated by Django 3.2.12 on 2022-04-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_project_admin_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultdataset',
            name='size',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
