# Generated by Django 3.2.16 on 2022-11-23 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20220406_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='projects.department'),
        ),
        migrations.AlterField(
            model_name='vaultdataset',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
