# Generated by Django 3.2.16 on 2023-01-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20221123_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchfolder',
            name='data_classification',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaultdataset',
            name='data_classification',
            field=models.CharField(default='', max_length=255),
        ),

    ]
