# Generated by Django 3.2.16 on 2023-01-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20230124_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchfolder',
            name='external_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researchfolder',
            name='internal_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='researchfolder',
            name='data_classification',
            field=models.CharField(default='Basic', max_length=255),
        ),
    ]
