# Generated by Django 4.2 on 2023-06-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20230125_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchstats',
            name='newest_file',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
