# Generated by Django 4.2.4 on 2023-08-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_researchstats_newest_file_vaultdataset_retention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultdataset',
            name='retention',
            field=models.IntegerField(default=10),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_code'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('abbreviation', 'faculty'), name='unique_abbreviation_faculty'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('vunetid',), name='unique_vunetid'),
        ),
    ]
