# Generated by Django 4.2.11 on 2024-03-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_vaultdataset_retention_budget_unique_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchfolder',
            name='sram_co_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchfolder',
            name='sram_memberships',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researchfolder',
            name='sram_open_invitations',
            field=models.IntegerField(default=0),
        ),

    ]
