# Generated by Django 4.2.15 on 2024-08-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_researchfolder_sram_co_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultdataset',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaultdataset',
            name='publication_access',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vaultdataset',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaultdataset',
            name='publication_doi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
